"""
partenit-init — scaffold a new Partenit robot safety project.

Usage:
    partenit-init my_robot
    partenit-init .            # init in current directory
    partenit-init              # prompts for project name
"""

from __future__ import annotations

import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Template content
# ---------------------------------------------------------------------------

_POLICIES_YAML = """\
# Starter safety policies for {project_name}
# Reference: https://github.com/GradeBuilderSL/partenit/tree/main/docs/guides/writing-policies.md

rules:
  - rule_id: human_proximity_slowdown
    name: "Human Proximity Speed Limit"
    priority: safety_critical
    provenance: "ISO 3691-4 section 5.2"
    condition:
      type: threshold
      metric: human.distance
      operator: less_than
      value: 1.5
      unit: meters
    action:
      type: clamp
      parameter: speed
      value: 0.3
      unit: m/s
    release:
      type: compound
      conditions:
        - type: threshold
          metric: human.distance
          operator: greater_than
          value: 2.0
      elapsed_seconds: 3

  - rule_id: emergency_stop
    name: "Emergency Stop — Human Too Close"
    priority: safety_critical
    provenance: "ISO 3691-4 section 5.3"
    condition:
      type: threshold
      metric: human.distance
      operator: less_than
      value: 0.8
      unit: meters
    action:
      type: block
"""

_MAIN_PY = """\
\"\"\"
{project_name} — guarded robot demo.

Generated by `partenit-init`. Run:
    pip install partenit
    python main.py
\"\"\"

from partenit.adapters import MockRobotAdapter
from partenit.agent_guard import GuardedRobot

# Simulated adapter — swap for ROS2Adapter / HTTPRobotAdapter on real hardware
adapter = MockRobotAdapter()
adapter.add_human("worker-1", x=1.2, y=0.0)   # worker 1.2 m ahead

robot = GuardedRobot(
    adapter=adapter,
    policy_path="policies/",
    session_name="{project_name}_session",
)

print("Sending navigate_to(zone='shipping', speed=2.0) ...")
decision = robot.navigate_to(zone="shipping", speed=2.0)

print(f"  allowed:          {{decision.allowed}}")
print(f"  modified_params:  {{decision.modified_params}}")
print(f"  risk_score:       {{decision.risk_score.value:.2f}}")
print(f"  policies fired:   {{decision.applied_policies}}")

print()
if not decision.allowed:
    print("Action was BLOCKED. Check policies/ to adjust thresholds.")
elif decision.modified_params:
    print("Action was MODIFIED (speed clamped). Guard is working correctly.")
else:
    print("Action was ALLOWED without modification.")

print()
print("Decision log stored in: decisions/{project_name}_session/")
print("Explain last decision:  partenit-why decisions/{project_name}_session/")
print("Watch live decisions:   partenit-watch decisions/")
"""

_GITIGNORE = """\
# Partenit decision logs (can be large, commit only when needed)
decisions/

# Python
__pycache__/
*.py[cod]
.venv/
*.egg-info/
dist/
"""


# ---------------------------------------------------------------------------
# Core logic
# ---------------------------------------------------------------------------


def scaffold(target: Path, project_name: str) -> list[tuple[Path, str]]:
    """
    Build the scaffold file list.

    Returns list of (path, label) tuples for the files created.
    """
    created: list[tuple[Path, str]] = []

    def _write(rel: str, content: str, label: str) -> None:
        dest = target / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        if not dest.exists():
            dest.write_text(content, encoding="utf-8")
            created.append((dest, label))
        else:
            created.append((dest, f"{label} (skipped, already exists)"))

    _write(
        "policies/policies.yaml",
        _POLICIES_YAML.format(project_name=project_name),
        "policies/policies.yaml",
    )

    # Create empty decisions dir with .gitkeep
    decisions_dir = target / "decisions"
    decisions_dir.mkdir(parents=True, exist_ok=True)
    gitkeep = decisions_dir / ".gitkeep"
    if not gitkeep.exists():
        gitkeep.write_text("", encoding="utf-8")
    created.append((decisions_dir, "decisions/"))

    _write(
        "main.py",
        _MAIN_PY.format(project_name=project_name),
        "main.py",
    )

    _write(".gitignore", _GITIGNORE, ".gitignore")

    return created


def _print_success_rich(target: Path, project_name: str, created: list[tuple[Path, str]]) -> None:
    from rich.console import Console
    from rich.panel import Panel
    from rich.text import Text

    console = Console()
    console.print()

    # Created files
    for _, label in created:
        console.print(f"  [green]✓[/] {label}")

    console.print()

    # Instructions
    rel = target.relative_to(Path.cwd()) if target.is_relative_to(Path.cwd()) else target
    steps = Text()
    steps.append(f"  cd {rel}\n", style="bold")
    steps.append("  pip install partenit\n", style="bold")
    steps.append("  python main.py\n", style="bold")

    console.print(
        Panel(
            steps,
            title=f"[bold green]{project_name}[/] is ready!",
            border_style="green",
            padding=(0, 1),
        )
    )

    console.print("  [dim]Docs:[/] https://github.com/GradeBuilderSL/partenit/tree/main/docs")
    console.print(
        "  [dim]Guide:[/] https://github.com/GradeBuilderSL/partenit/blob/main/docs/guides/writing-policies.md\n"
    )


def _print_success_plain(target: Path, project_name: str, created: list[tuple[Path, str]]) -> None:
    print()
    for _, label in created:
        print(f"  OK  {label}")
    print()
    rel = target.relative_to(Path.cwd()) if target.is_relative_to(Path.cwd()) else target
    print(f"Project '{project_name}' is ready!")
    print()
    print("  Next steps:")
    print(f"    cd {rel}")
    print("    pip install partenit")
    print("    python main.py")
    print()
    print("  Docs: https://github.com/GradeBuilderSL/partenit/tree/main/docs")
    print()


def run_init(project_name: str | None = None) -> int:
    """Main init logic — called by CLI entry point."""
    # Determine project name and target directory
    if project_name is None or project_name == ".":
        target = Path.cwd()
        name = target.name
    else:
        target = Path(project_name).resolve()
        name = target.name

    try:
        target.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        print(f"ERROR: cannot create directory {target}: {exc}", file=sys.stderr)
        return 1

    created = scaffold(target, name)

    try:
        _print_success_rich(target, name, created)
    except ImportError:
        _print_success_plain(target, name, created)

    return 0


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(
        prog="partenit-init",
        description="Scaffold a new Partenit robot safety project.",
    )
    parser.add_argument(
        "project_name",
        nargs="?",
        default=None,
        help="Project directory name (default: current directory)",
    )
    args = parser.parse_args()
    sys.exit(run_init(args.project_name))


if __name__ == "__main__":
    main()
